version: '3.8'
services:
  postgres:
    container_name: rockethelp
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
volumes:
  postgres:
